### ISSUE TITLE
Please add support pytest

### ISSUE THREAD

**Issue by qwertzy-antonio-godinho** [vipmax/edgo#1]
Please add support for python pytest test execution.
Changing internal/ui/tests.go line 158 unitest to pytest seems to work ok, but would be great to have support for setting the test runner in the configuration along with it's flags.

**Comment by vipmax** [comment]
<img width="1316" alt="Screenshot 2023-10-06 at 4 38 17 PM" src="https://github.com/vipmax/edgo/assets/4265482/d3a5d678-fb55-4d6a-8b10-f40e712e6853">

**Comment by vipmax** [comment]
changed python tests to pytest by default
