### ISSUE TITLE
python tests incorrectly detected

### ISSUE THREAD

**Issue by qwertzy-antonio-godinho** [vipmax/edgo#2]
Edgo seems to incorrectly mark some python code as a test. See attached picture for example, line 1 and line 11 are not tests
![Screenshot_20231003-235520.png](https://github.com/vipmax/edgo/assets/74644600/2cdfcb19-7e73-46f0-985f-0fc27e4b6724)

**Comment by vipmax** [comment]
<img width="1052" alt="Screenshot 2023-10-06 at 4 16 46 PM" src="https://github.com/vipmax/edgo/assets/4265482/3bed3ac8-84bf-4a5d-a20f-1402dca8d79a">

**Comment by qwertzy-antonio-godinho** [comment]
Hi, thank you for looking at this, but there is still one instance where it wrongly IDs a test where there is none, line 1. It seems that for some reason edgo always marks the first line as a test. It can be also seen on your screen shot.
