### ISSUE TITLE
Ability to search/fuzzy find in the output view

### ISSUE THREAD

**Issue by qwertzy-antonio-godinho** [vipmax/edgo#6]
Sometimes running a script outputs too much text in the output view window. Would you consider implementing some sort of ability to find/search for text in the output view window?

**Comment by vipmax** [comment]
It is possible to filter by file extension, simply add "-f .go" to the query

<img width="1341" alt="Screenshot 2023-10-15 at 1 32 45 PM" src="https://github.com/vipmax/edgo/assets/4265482/6d3eae9f-a600-49ad-a9e3-c42b8db99dd7">

**Comment by qwertzy-antonio-godinho** [comment]
> It is possible to filter by file extension, simply add "-f .go" to the query
> 
> <img width="1341" alt="Screenshot 2023-10-15 at 1 32 45 PM" src="https://github.com/vipmax/edgo/assets/4265482/6d3eae9f-a600-49ad-a9e3-c42b8db99dd7">
> 

I meant searching the output pane after you execute a program or a test for some strings, sometimes I run tests that fail and the output shows me the debug messages and just want to be able to search the info for specific strings without having to copy the output to a text file in another text editor. Some terminals allow you to search but depending on the amount of text output by for instance pytest with the debug messages all the text might not be displayed due to the output pane size and all of the output can't be searched from within the terminal search.

**Comment by vipmax** [comment]
done
here is screenshot

<img width="1341" alt="Screenshot 2023-10-15 at 6 58 50 PM" src="https://github.com/vipmax/edgo/assets/4265482/305b7b21-c730-47e8-9261-28b642559d69">

**Comment by qwertzy-antonio-godinho** [comment]
> done
> here is screenshot
> 
> <img width="1341" alt="Screenshot 2023-10-15 at 6 58 50 PM" src="https://github.com/vipmax/edgo/assets/4265482/305b7b21-c730-47e8-9261-28b642559d69">
> 

Thank you, this issue can be closed
